from interface.Detection_retina.model import ResNet
from interface.Detection_retina.model import PyramidFeatures
from interface.Detection_retina.model import RegressionModel
from interface.Detection_retina.model import ClassificationModel